version: "3.8"

services:
  postgres:
    image: postgres:16-alpine
    container_name: easyfood-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: dbeasyfood
      POSTGRES_USER: easyfood
      POSTGRES_PASSWORD: easyfood
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - easyfood-db-data:/var/lib/postgresql/data
    labels:
      # Allows Spring Boot to auto-configure a DataSource from this container when running with spring-boot-docker-compose
      org.springframework.boot.service-connection: postgres

  app:
    build: .
    container_name: easyfood-app
    restart: unless-stopped
    environment:
      SPRING_PROFILES_ACTIVE: prd
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/dbeasyfood
      SPRING_DATASOURCE_USERNAME: easyfood
      SPRING_DATASOURCE_PASSWORD: easyfood

      JAVA_OPTS: -Xms256m -Xmx512m
    ports:
      - "8090:8090"
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  easyfood-db-data:
